### ISSUE TITLE
Create Shell Script to install Hilary & Dependencies

### ISSUE THREAD

**Issue by wbbarr** [GatechVIP/no-code#18]
The Hilary install process seems fairly complicated, given that there are a large number of dependencies.  We could use a shell script that can be run to install Hilary and its dependencies, preferably in a manner similar to the quick setup used for Nakamura, the old backend that was deprecated in favor of Hilary.  You can find the setup script at https://raw.github.com/gist/3212977/sakaioae-quickdevsetup.sh

This would be very helpful, and could be a nice contribution back upstream to the core team.

**Comment by pongad** [comment]
I've been thinking about this a little bit. I'm wondering whether installing some dependencies from source will be a smart idea. From what I know, installation varies a little bit with distributions, installing from source has the benefit of being able to do "make install". If we are going with this, installation process might take a little time. (Once again, I blame C++)

**Comment by pongad** [comment]
So, instead of watching TV like a sane person would, I have been creating and recreating the install script. I this I got the last one (https://github.com/pongad/buildsh) almost right. To my sleep-deprived brain, everything looks like it should work. Two issues remain though:
1) This script builds Cassandra from source. The binary can only be downloaded through a load balancer, and I don't know how to get the script to navigate it.
2) I didn't want to append oae.mine.com to the /etc/hosts. Since the script would be adding one copy of that per run. I ran the script about 5 times on my VM just now, so that felt like a bad idea.

Since Hilary is still not quite working, can anyone think of a test for this?

**Comment by wbbarr** [comment]
I'm currently working with Stuart to resolve the grunt issues.  

Grunt was just updated.  The correct install command is now `npm install -g grunt-cli`

**Comment by wbbarr** [comment]
FYI, grunt upgrade from .3 to .4 has some breaking changes.  See https://github.com/sakaiproject/3akai-ux/issues/2609 for more information.

**Comment by pongad** [comment]
You try to use grunt to solve a problem, and now you have two.

**Comment by pongad** [comment]
I haven't have time to look into this issue yet, I should be able to work on it before Wednesday.

**Comment by pongad** [comment]
New installation "script": https://gist.github.com/pongad/8bb0e81f439fb621ed75
I wrote it in D; don't judge me. I got some HTML out of it, but it's not appear to be working. Is the dependency bug still there?

**Comment by pongad** [comment]
I assume this is not used anymore, can someone close this issue? :smile:
