### ISSUE TITLE
Edit Collaboration Survey

### ISSUE THREAD

**Issue by robertam3** [GatechVIP/no-code#2]
The survey developed last week has a lot of text boxes for yes/no questions. We need to make sure that the survey is convenient to fill out and gives us a good idea of how people use Google Docs.

**Comment by robertam3** [comment]
The survey is available for review here: https://docs.google.com/spreadsheet/viewform?fromEmail=true&formkey=dHRQczV6TThhV3JVTTFySUdrcHVNREE6MQ

Slightly different questions are asked if you have not used a collaboration tool before.
@vishwajac

**Comment by khomotso** [comment]
A couple comments:

I think questions framed in terms of 'did you like' or 'did you not like' are of limited value. They focus on snap impressions, tend to focus on personal preferences rather than what turns out to be useful, and are limited to the things the responder gives conscious attention to.

You can get the same or better information from a question like: describe to us a learning experience where using Google docs was helpful, and explain why it was helpful.

On the negative side, it might be: within this learning experience (above) which parts of Google docs were frustrating or didn't allow you to do what you wanted?

**Comment by robertam3** [comment]
I've just updated the survey with the following revised questions:

Think of a learning experience where using a collaboration tool was helpful, and explain how it was helpful.
What made your experience easier, faster, or more enjoyable?

Regarding the same learning experience you described above, what was frustrating or prevented you from accomplishing something?
Were you able to overcome any obstacles you faced and, if so, how?
