### ISSUE TITLE
Survey Distribution

### ISSUE THREAD

**Issue by robertam3** [GatechVIP/no-code#4]
Determine the best method for distributing the collaboration/Google Doc survey and send it out. Also keep track of the survey's progress (are enough people completing it, are we getting good results, etc.) Talk to the person editing the survey to find out when to start distribution. You can still determine the best way to distribute it, however, before the survey is done.

**Comment by vishwajac** [comment]
Just sent out the survey to about 20 people by email. Will be meeting about 5 people tomorrow to ask the questions in person. Expect at least 10 solid responders for the survey by Tuesday's meeting.

**Comment by robertam3** [comment]
Great. After you meet with the 5 people tomorrow, we can get some feedback on the survey itself and see if we should make any changes to it before we send it off to anyone else (if needed).

**Comment by vishwajac** [comment]
Got to interview 6 people. Will try and get the responses to you guys this evening. I did not end up sending out the actual annotation survey because of the sheer number of surveys I've already bombarded people with this week (some of my other classes required us to send out surveys as well) so if a couple of other people can take up the task of sending out the electronic version of this survey to 5-6 other people it may help. I personally think we have enough information from the interviews and our previous survey.
